name: video_player_example
description: Demonstrates how to use the video_player plugin.

dependencies:
  flutter:
    sdk: flutter
  video_player_x:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: "^0.2.0"
  test: any
  pedantic: ^1.8.0

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

flutter:
  uses-material-design: true
  assets:
   - assets/flutter-mark-square-64.png
   - assets/Butterfly-209.mp4
   - assets/bumble_bee_captions.srt
